import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

// Define the group names and the corresponding entities
const groups = {
  'Sales and Customers Management': [
    'salesOrder.model.ts',
    'quote.model.ts',
    'customer.model.ts',
    'customer-brand.model.ts',
    'customer-payment.model.ts',
    'customer-invoice.model.ts',
    'order-detail.model.ts',
    'order-status.model.ts',
    'discount.model.ts',
    'price-history.model.ts',
    'shipping-details.model.ts',
    'return-order.model.ts',
    'customer-contact.model.ts',
  ],
  'Procurement and Supplier Management': [
    'supplier.model.ts',
    'supplierAudit.model.ts',
    'supplierScoreCard.model.ts',
    'purchaseOrder.model.ts',
    'purchaseOrderStatus.model.ts',
    'receiving.model.ts',
    'supplierCertificate.model.ts',
    'purchaseOrderCOA.model.ts',
    'purchaseOrderShipment.model.ts',
    'supplierAgreement.model.ts',
    'supplierInvoice.model.ts',
    'supplierPerformance.model.ts',
    'purchaseOrderTracking.model.ts',
  ],
  'Production and Work Orders': [
    'workOrder.model.ts',
    'batch.model.ts',
    'batchRecord.model.ts',
    'productionStage.model.ts',
    'workOrderStatus.model.ts',
    'productionSchedule.model.ts',
    'mixingRecord.model.ts',
    'siftingRecord.model.ts',
    'encapsulationRecord.model.ts',
    'packagingRecord.model.ts',
    'bottlingRecord.model.ts',
    'batchStepAudit.model.ts',
    'productionOutput.model.ts',
    'wasteRecord.model.ts',
    'reworkOrder.model.ts',
    'certificateOfComposition.model.ts',
    'workOrderAssignment.model.ts',
    'batchYield.model.ts',
    'machineUtilization.model.ts',
  ],
  'Inventory and Warehouse Management': [
    'inventory-item.model.ts',
    'warehouse.model.ts',
    'warehouse-location.model.ts',
    'lot.model.ts',
    'raw-material.model.ts',
    'work-in-progress.model.ts',
    'finished-good.model.ts',
    'packaging-material.model.ts',
    'inventory-item-quantity.model.ts',
    'inventory-item-price.model.ts',
    'inventory-movement.model.ts',
    'inventory-status.model.ts',
    'stock-reorder.model.ts',
    'inventory-expiration.model.ts',
    'inventory-adjustment.model.ts',
    'inventory-forecasting.model.ts',
    'inventory-return.model.ts',
    'cycle-counting.model.ts',
    'inventory-audit.model.ts',
  ],
  'Product Development and SKU Management': [
    'sku.model.ts',
    'product-type.model.ts',
    'formula.model.ts',
    'formula-material.model.ts',
    'bill-of-materials.model.ts',
    'product-price.model.ts',
    'formula-comment.model.ts',
    'formula-audit.model.ts',
    'product-development-request.model.ts',
    'prototype.model.ts',
    'packaging-design.model.ts',
    'regulatory-approval.model.ts',
    'product-lifecycle.model.ts',
    'sample-request.model.ts',
    'product-costing.model.ts',
  ],
  'Quality Assurance and Compliance': [
    'certificate-of-analysis.model.ts',
    'batch-audit.model.ts',
    'lot-audit.model.ts',
    'quality-audit.model.ts',
    'standard-operating-procedure.model.ts',
    'retains.model.ts',
    'compliance-audit.model.ts',
    'non-conformance-report.model.ts',
    'compliance-report.model.ts',
    'deviation.model.ts',
    'corrective-action-request.model.ts',
    'regulatory-submission.model.ts',
  ],
  'Asset Management and Maintenance': [
    'asset.model.ts',
    'asset-maintenance-record.model.ts',
    'asset-cleaning-record.model.ts',
    'machine-operation-log.model.ts',
    'calibration-record.model.ts',
    'maintenance-schedule.model.ts',
    'asset-depreciation.model.ts',
    'asset-utilization.model.ts',
    'spare-parts-inventory.model.ts',
    'asset-inspection.model.ts',
    'machine-downtime-log.model.ts',
    'energy-consumption-log.model.ts',
    'asset-repair-request.model.ts',
    'asset-warranty.model.ts',
  ],
  'Human Resources and Training': [
    'user.model.ts',
    'user-role.model.ts',
    'user-group.model.ts',
    'training-record.model.ts',
    'shift-schedule.model.ts',
    'attendance.model.ts',
    'employee-performance.model.ts',
    'role-permissions.model.ts',
    'time-off-request.model.ts',
    'certification.model.ts',
    'payroll.model.ts',
    'hr-incident-log.model.ts',
    'onboarding-checklist.model.ts',
    'termination-checklist.model.ts',
  ],
  'Billing and Financial Management': [
    'customer-invoice.model.ts',
    'supplier-invoice.model.ts',
    'payment.model.ts',
    'financial-report.model.ts',
    'revenue-record.model.ts',
    'expense-report.model.ts',
    'tax-record.model.ts',
    'payment-terms.model.ts',
    'credit-memo.model.ts',
    'ledger.model.ts',
    'budget.model.ts',
    'cost-center.model.ts',
    'account-reconciliation.model.ts',
    'fixed-asset-management.model.ts',
    'bank-transaction.model.ts',
    'deferred-revenue.model.ts',
  ],
  'Reporting and Analytics': [
    'operational-report.model.ts',
    'sales-report.model.ts',
    'financial-report.model.ts',
    'production-report.model.ts',
    'inventory-report.model.ts',
    'customer-report.model.ts',
    'supplier-report.model.ts',
    'audit-log.model.ts',
    'key-performance-indicator.model.ts',
    'forecasting-report.model.ts',
    'capacity-report.model.ts',
    'compliance-report.model.ts',
    'labor-utilization-report.model.ts',
    'risk-assessment.model.ts',
  ],
  'Customer Portal': [
    'customer-profile.model.ts',
    'customer-order.model.ts',
    'quote.model.ts',
    'payment-history.model.ts',
    'invoice.model.ts',
    'order-tracking.model.ts',
    'return-request.model.ts',
    'customer-ticket.model.ts',
    'customer-feedback.model.ts',
    'customer-credit.model.ts',
  ],
  'Product Lifecycle Management (PLM)': [
    'product.model.ts',
    'formula.model.ts',
    'product-version.model.ts',
    'lifecycle-stage.model.ts',
    'change-request.model.ts',
    'change-approval.model.ts',
    'product-obsolescence.model.ts',
    'compliance-certification.model.ts',
    'market-feedback.model.ts',
    'product-testing.model.ts',
    'recall-record.model.ts',
    'sustainability-score.model.ts',
  ],
  'Document Management': [
    'document.model.ts',
    'document-version.model.ts',
    'document-approval.model.ts',
    'document-tag.model.ts',
    'retention-policy.model.ts',
    'document-audit-log.model.ts',
  ],
  'Regulatory and Compliance': [
    'fda-compliance.model.ts',
    'gmp-certification.model.ts',
    'environmental-compliance.model.ts',
    'audit-log.model.ts',
    'compliance-checklist.model.ts',
    'regulatory-submission.model.ts',
    'label-compliance.model.ts',
    'product-traceability.model.ts',
    'non-compliance-report.model.ts',
    'risk-assessment.model.ts',
  ],
  'System Administration and Security': [
    'user-permissions.model.ts',
    'role-assignments.model.ts',
    'system-log.model.ts',
    'data-backup.model.ts',
    'security-incident.model.ts',
    'two-factor-authentication.model.ts',
    'api-usage-log.model.ts',
    'sla.model.ts',
    'performance-monitoring.model.ts',
    'user-session.model.ts',
    'password-policy.model.ts',
    'license-management.model.ts',
    'audit-trail.model.ts',
  ],
  'Integration and API Management': [
    'integration.model.ts',
    'api-key-management.model.ts',
    'webhook.model.ts',
    'data-mapping.model.ts',
    'integration-log.model.ts',
    'edi.model.ts',
    'connector.model.ts',
    'oauth-token-management.model.ts',
    'rate-limiting-config.model.ts',
  ],
  'Supply Chain Management': [
    'logistics.model.ts',
    'transportation-request.model.ts',
    'shipping-provider.model.ts',
    'shipment.model.ts',
    'freight-cost.model.ts',
    'customs-declaration.model.ts',
    'route-optimization.model.ts',
    'delivery-status.model.ts',
    'supply-chain-risk-assessment.model.ts',
    'container-tracking.model.ts',
    'carrier-performance.model.ts',
  ],
  'Project Management and Task Tracking': [
    'project.model.ts',
    'task.model.ts',
    'task-dependency.model.ts',
    'milestone.model.ts',
    'project-budget.model.ts',
    'task-assignment.model.ts',
    'timesheet.model.ts',
    'resource-allocation.model.ts',
    'risk-management.model.ts',
    'project-status.model.ts',
    'issue-log.model.ts',
  ],
  'Advanced Analytics and AI Integration': [
    'machine-learning-model.model.ts',
    'predictive-maintenance.model.ts',
    'inventory-forecasting-model.model.ts',
    'customer-behavior-model.model.ts',
    'demand-planning.model.ts',
    'cost-analysis-model.model.ts',
    'ai-chatbot.model.ts',
    'anomaly-detection.model.ts',
    'sentiment-analysis.model.ts',
    'pricing-optimization.model.ts',
  ],
  'Environmental and Sustainability Management': [
    'environmental-impact.model.ts',
    'sustainability-report.model.ts',
    'waste-management.model.ts',
    'energy-consumption.model.ts',
    'carbon-footprint.model.ts',
    'sustainability-initiatives.model.ts',
    'green-certification.model.ts',
    'recycling-program.model.ts',
    'supplier-sustainability.model.ts',
  ],
  'Customer Experience Management (CXM)': [
    'customer-feedback.model.ts',
    'customer-survey.model.ts',
    'nps.model.ts',
    'support-ticket.model.ts',
    'customer-retention.model.ts',
    'customer-complaints.model.ts',
    'loyalty-program.model.ts',
    'customer-engagement.model.ts',
    'customer-satisfaction-score.model.ts',
    'referral-program.model.ts',
    'personalization-engine.model.ts',
  ],
  'Research and Development (RandD) Management': [
    'r-and-d-project.model.ts',
    'experiment.model.ts',
    'prototype-development.model.ts',
    'material-testing.model.ts',
    'r-and-d-investment.model.ts',
    'innovation-pipeline.model.ts',
    'patent-management.model.ts',
    'compliance-testing.model.ts',
    'formula-innovation.model.ts',
    'technology-transfer.model.ts',
    'project-stage-gate.model.ts',
  ],
  'Subscription and Recurring Billing': [
    'subscription-plan.model.ts',
    'recurring-billing.model.ts',
    'subscription-invoice.model.ts',
    'trial-management.model.ts',
    'auto-renewal.model.ts',
    'cancellation-request.model.ts',
    'usage-tracking.model.ts',
    'subscription-upgrade.model.ts',
    'billing-history.model.ts',
    'customer-subscription.model.ts',
  ],
  'Knowledge Management': [
    'knowledge-base.model.ts',
    'training-material.model.ts',
    'faq.model.ts',
    'document-library.model.ts',
    'best-practice.model.ts',
    'feedback-loop.model.ts',
  ],
  'IT and Infrastructure Management': [
    'it-asset.model.ts',
    'network-monitoring.model.ts',
    'incident-log.model.ts',
    'system-update.model.ts',
    'access-control.model.ts',
    'license-tracking.model.ts',
    'data-backup-schedule.model.ts',
  ],
  'Multi-Currency and Global Operations': [
    'currency.model.ts',
    'exchange-rate.model.ts',
    'global-tax-rules.model.ts',
    'global-shipping.model.ts',
    'localization-settings.model.ts',
    'regional-compliance.model.ts',
    'international-invoice.model.ts',
    'customs-management.model.ts',
    'global-supplier.model.ts',
  ],
  'Partnership and Channel Management': [
    'partner-profile.model.ts',
    'partner-agreement.model.ts',
    'partner-performance.model.ts',
    'revenue-share.model.ts',
    'channel-sales-order.model.ts',
    'partner-support-ticket.model.ts',
    'commission-payout.model.ts',
  ],
  'E-Commerce and Digital Sales': [
    'online-order.model.ts',
    'digital-product.model.ts',
    'payment-gateway.model.ts',
    'cart-abandonment.model.ts',
    'discount-code.model.ts',
    'shipping-method.model.ts',
    'return-request.model.ts',
    'product-review.model.ts',
  ],
  'Social Media and Brand Monitoring': [
    'social-media-account.model.ts',
    'post-scheduler.model.ts',
    'engagement-tracker.model.ts',
    'influencer-campaign.model.ts',
    'brand-mentions.model.ts',
    'social-media-report.model.ts',
  ],
  'Artificial Intelligence and Machine Learning Operations (AIOps)': [
    'ai-ops-model.model.ts',
    'ai-anomaly-detection.model.ts',
    'ai-predictive-model.model.ts',
    'ai-demand-forecast.model.ts',
    'ai-recommendation-engine.model.ts',
    'ai-chatbot-support.model.ts',
    'ai-ops-automation.model.ts',
  ],
  'Data Science and Advanced Analytics': [
    'data-warehouse.model.ts',
    'predictive-analytics-model.model.ts',
    'data-visualization.model.ts',
    'big-data-management.model.ts',
    'data-science-project.model.ts',
    'data-analysis-report.model.ts',
    'data-mining.model.ts',
    'machine-learning-integration.model.ts',
  ],
  'Customer Relationship Management (CRM)': [
    'lead.model.ts',
    'opportunity.model.ts',
    'customer-interaction-log.model.ts',
    'campaign-management.model.ts',
    'customer-segmentation.model.ts',
    'customer-loyalty.model.ts',
    'sales-pipeline.model.ts',
    'sales-stage.model.ts',
    'customer-follow-up.model.ts',
    'customer-retention-score.model.ts',
    'customer-engagement-metrics.model.ts',
    'crm-integration.model.ts',
  ],
  'Multi-Company / Multi-Division Management': [
    'company.model.ts',
    'division.model.ts',
    'brand.model.ts',
    'intercompany-transaction.model.ts',
    'intercompany-billing.model.ts',
    'consolidated-financials.model.ts',
    'cross-company-inventory.model.ts',
    'shared-services.model.ts',
    'multi-currency-support.model.ts',
    'company-hierarchy.model.ts',
  ],
  'Customization and Workflow Automation': [
    'custom-field.model.ts',
    'custom-form.model.ts',
    'workflow-rule.model.ts',
    'business-rule.model.ts',
    'approval-workflow.model.ts',
    'notification-rule.model.ts',
    'task-automation.model.ts',
    'custom-report.model.ts',
    'data-export.model.ts',
    'system-customization.model.ts',
  ],
  'Legal and Compliance Management': [
    'contract.model.ts',
    'contract-renewal.model.ts',
    'legal-case.model.ts',
    'regulatory-filing.model.ts',
    'compliance-checklist.model.ts',
    'litigation-log.model.ts',
    'legal-review-request.model.ts',
    'legal-risk-assessment.model.ts',
    'ip-compliance.model.ts',
    'compliance-reminder.model.ts',
  ],
  'Marketing Management': [
    'marketing-campaign.model.ts',
    'campaign-budget.model.ts',
    'content-management.model.ts',
    'lead-generation.model.ts',
    'email-marketing.model.ts',
    'social-media-management.model.ts',
    'seo-analytics.model.ts',
    'ppc.model.ts',
    'marketing-roi.model.ts',
    'event-management.model.ts',
    'influencer-marketing.model.ts',
  ],
};

// Function to convert kebab-case to PascalCase (LikeThis)
const toPascalCase = (str: string) => {
  return str
    .replace(/(^\w|-\w)/g, (clear) => clear.replace('-', '').toUpperCase())
    .replace('.model.ts', '');
};

// Function to create the necessary directories and files for each group
const createGroupFiles = (groupName: string, files: string[]) => {
  // Convert spaces to kebab-case for the directory name
  const groupDir = join(
    targetDir,
    groupName.replace(/\s+/g, '-').toLowerCase()
  );
  if (!existsSync(groupDir)) {
    mkdirSync(groupDir, { recursive: true });
    console.log(`Directory created: ${groupDir}`);
  }

  files.forEach((file) => {
    const filePath = join(groupDir, file);
    const className = toPascalCase(file); // Convert kebab-case to PascalCase for class name
    const content = `// ${file} - Model definition\n\nexport class ${className} {\n\n}`;
    writeFileSync(filePath, content);
    console.log(`Created file: ${filePath}`);
  });
};

// Define the target directory for the generated files
const targetDir = './src/infrastructure/persistence/entities';

// Loop through the groups and create the files for each
Object.entries(groups).forEach(([groupName, files]) => {
  createGroupFiles(groupName, files);
});

console.log('All files generated successfully!');
