#!/bin/sh

# Do not allow push to protected branches
protected_branches='feature/* | dev | qa/* | release_candidate/* | main | hotfix/*'

current_branch=$(git rev-parse --abbrev-ref HEAD)

# Prevent direct push to protected branches
if echo "$current_branch" | grep -Eq "$protected_branches"; then
  echo "Error: Direct push to $current_branch is not allowed."
  echo "Please use pull requests for changes to this branch."
  exit 1
fi

# Allow commit messages that are merge commits to bypass Jira issue ID check
while read local_ref local_sha remote_ref remote_sha; do
  COMMITS=$(git rev-list $remote_sha..$local_sha)
  for COMMIT in $COMMITS; do
    MESSAGE=$(git log --format=%B -n 1 $COMMIT)
    
    # Skip the check for merge commits
    if [[ $MESSAGE =~ ^Merge ]]; then
      continue
    fi
    
    # Enforce Jira issue ID in other commit messages
    if [[ ! $MESSAGE =~ (Merge|NFG-[0-9]+) ]]; then
      echo "Error: Commit message '$MESSAGE' does not contain a Jira issue ID (NFG-<issue-number>)."
      exit 1
    fi
  done
done
