name: Enforce Branch Naming

on:
  push:
    branches:
      - "*"

jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enforce branch naming convention
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          PATTERN="^(feature|story|hotfix)/NFG-[0-9]+-.+"
          if [[ ! $BRANCH_NAME =~ $PATTERN ]]; then
            echo "Error: Branch name '$BRANCH_NAME' does not follow the naming convention."
            exit 1
          fi
