name: Enforce Commit Message

on:
  push:
    branches:
      - "*"

jobs:
  check-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enforce commit message Jira issue ID
        run: |
          COMMITS=$(git rev-list --all)
          for COMMIT in $COMMITS; do
            MESSAGE=$(git log --format=%B -n 1 $COMMIT)
            if [[ ! $MESSAGE =~ (Merge|NFG-[0-9]+) ]]; then
              echo "Error: Commit message '$MESSAGE' does not contain a Jira issue ID (NFG-<issue-number>)."
              exit 1
            fi
          done
