name: Create PR on Push to Branch

on:
  push:
    branches:
      - "NFG-*"

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          source_branch: ${{ github.ref }}
          destination_branch: development
          pr_title: "Merge ${{ github.ref }} into development"
          pr_body: "Automated PR to merge changes from feature to development"
